---
- name: haveged
  hosts: rancherserver
  sudo: True
  tasks:
  - name: Install docker-py
    pip: name=docker-py version=1.1.0
  - name: Entropy maker HAVEGED
    docker:
      name: havegedocker
      image: joshuacox/havegedocker:latest
      privileged: yes
      state: reloaded
