---
- name: RancherOS
  hosts: rancheros
  sudo: True
  tasks:
  - name: Install docker-py
    pip: name=docker-py version=1.1.0
  - name: RancherOS rancher/server
    docker:
      name: rancherserver
      image: rancher/server
      state: reloaded
      restart_policy: always
      ports:
      - "8080:8080"
